title: "Senior Project"
description: "Senior Project - Vivian Collins"
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/HC26-Collins-Vivian-Senior-Project"


plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true
